name: 'terraform plan'

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]
  workflow_dispatch: {}
  
env:
  TERRAFORM_VERSION: '1.10.2'
  TERRAFORM_VAR_FILE: 'terraform.auto.tfvars'
  TF_LOG: INFO

permissions:
  contents: read
  id-token: write

jobs:
  push_checks:
    name: 'Plan Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.event.pull_request.head.ref || 'main' }}

      # WIF
      - name: GCP Workload Identity Federation connection
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ env.WIF_PROVIDER }}
          service_account: ${{ env.WIF_SERVICE_ACCOUNT }}

      - name: setup terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: terraform init
        id: init
        run: |
          terraform init -backend-config="bucket=${{ env.TERRAFORM_STATE_FILE_BUCKET }}" -backend-config="prefix=${{ github.repository }}/${{ github.ref_name || 'main' }}" 

      - name: terraform plan
        id: plan
        run: |
          terraform plan -var-file=${{ env.TERRAFORM_VAR_FILE }}