name: 'terraform plan'

on:
  push:
    branches:
      - main

env:
  TERRAFORM_STATE_FILE_BUCKET: ${{ secrets.TERRAFORM_STATE_FILE_BUCKET }}
  WIF_PROVIDER: ${{ secrets.WIF_PROVIDER }} # Workload Identity Federation Provider
  WIF_SERVICE_ACCOUNT: ${{ secrets.WIF_SERVICE_ACCOUNT }} # Deployment Service Account
  
  TERRAFORM_VERSION: '1.12.0' # This should ideally be updated, e.g., to '1.8.0'
  TERRAFORM_VAR_FILE: 'terraform.auto.tfvars' # Terraform variable file to look for

  TF_LOG: INFO
  
permissions:
  contents: read
  id-token: write

jobs:  
  terraform_plan:
    name: 'terraform plan'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # WIF
      - name: GCP Workload Identity Federation Connection
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ env.WIF_PROVIDER }}
          service_account: ${{ env.WIF_SERVICE_ACCOUNT }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform Init
        id: init
        # working-directory: ./environments/prod
        run: |
          terraform init -backend-config="bucket=${{ env.TERRAFORM_STATE_FILE_BUCKET }}"

      # Generates an execution plan for Terraform
      - name: Terraform Plan
        id: plan
        # working-directory: ./environments/prod
        run: |
          terraform plan -var-file=${{ env.TERRAFORM_VAR_FILE }} -out=tfplan