name: 'Reusable Terraform Plan'

on:
  push:
    branches:
      - main
jobs:
  terraform_plan:
    name: 'Terraform Plan Example'
    uses: bjbloemker-google/gcp-terraform-action-workflows/.github/workflows/plan.yaml@feat/reusable-terraform-workflows # Adjust ref as needed, e.g., @main or @v1.0.0
    with:
      # Optional Inputs (examples show defaults or common usage):
      # terraform_version: '1.12.0' # Default: '1.12.0'
      # working_directory: '.'      # Default: '.' (current directory)
      # terraform_var_file: 'terraform.auto.tfvars' # Default: 'terraform.auto.tfvars'

      # Required Inputs (replace with your actual secret names if different):
      gcp_wif_provider: ${{ secrets.GCP_WIF_PROVIDER }}
      gcp_wif_service_account: ${{ secrets.GCP_WIF_SERVICE_ACCOUNT }}
      gcp_terraform_state_bucket: ${{ secrets.GCP_TERRAFORM_STATE_BUCKET }}
    
    secrets: inherit # Recommended for simplicity if secrets are defined at the repository or organization level.
